# Generated by Django 4.1.7 on 2023-03-30 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=16)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('narx', models.PositiveIntegerField()),
                ('olchov', models.CharField(max_length=15)),
                ('kelgan_sana', models.DateTimeField(auto_now_add=True)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='asosiy_app.ombor')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('manzil', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=25)),
                ('tel', models.CharField(max_length=16)),
                ('qarz', models.PositiveIntegerField(default=0)),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clintlar', to='asosiy_app.ombor')),
            ],
        ),
    ]
